#!/bin/bash
# nightly-briefing.sh — Generate the morning briefing digest
# Run: bash scripts/nightly-briefing.sh
# Output: memory/nightly-briefing-YYYY-MM-DD.md

MEMORY_DIR="$HOME/.openclaw/workspace/memory"
TODAY="$(date +%Y-%m-%d)"
BRIEFING_FILE="$MEMORY_DIR/nightly-briefing-$TODAY.md"

echo "📋 Generating nightly briefing for $TODAY..."

# Build the entire briefing in Python to avoid all bash quoting hell
python3 << 'PYEOF'
import os
from datetime import date, timedelta

memory_dir = os.path.expanduser("~/.openclaw/workspace/memory")
pain_file = os.path.expanduser("~/.openclaw/workspace/tmp/overnight-pain.json")
today = date.today().strftime("%Y-%m-%d")
briefing_file = os.path.join(memory_dir, f"nightly-briefing-{today}.md")

def extract_section_md(filepath, marker):
    """Extract a markdown section by heading name (fuzzy match)."""
    if not os.path.exists(filepath):
        return None
    with open(filepath) as f:
        lines = f.readlines()
    in_section = False
    result = []
    for line in lines:
        stripped = line.rstrip()
        if stripped.startswith("## ") or stripped.startswith("##\t"):
            hdr = stripped.lstrip("# \t")
            if marker.lower() in hdr.lower():
                in_section = True
                continue
            elif in_section:
                break
        elif in_section:
            result.append(stripped)
    return "\n".join(result) if result else None

# Load pain data
cron_errors = []
confetti = {}
recent_builds = []
try:
    import json
    with open(pain_file) as f:
        pain = json.load(f)
    cron_errors = pain.get("cron_errors", [])
    confetti = pain.get("confetti_closet", {})
    recent_builds = pain.get("recent_builds", [])
except:
    pass

# Sections
today_file = os.path.join(memory_dir, "daily", f"{today}.md")
changes = extract_section_md(today_file, "What Changed") or "_No changes logged today._"
agenda = extract_section_md(today_file, "Agenda") or "_No agenda found._"
tomorrow = extract_section_md(today_file, "Tomorrow") or "_No lookahead._"

# Cron errors
if cron_errors:
    cron_section = "\n".join(f"- **{e.get('name', '?')}**: {e.get('error', 'unknown')}" for e in cron_errors)
else:
    cron_section = "_No cron errors detected._"

# Active tasks
active_tasks_file = os.path.join(memory_dir, "tasks", "active-tasks.md")
if os.path.exists(active_tasks_file):
    with open(active_tasks_file) as f:
        active_tasks = "\n".join(f.read().splitlines()[:25])
else:
    active_tasks = "_No active-tasks.md found._"

# Recent learnings
learnings_file = os.path.join(memory_dir, "learnings-log.md")
try:
    with open(learnings_file) as f:
        lines = f.read().splitlines()
    recent = [l for l in lines if l.strip() and ("## " in l or "- **" in l or "**20" in l)][-15:]
    learnings_section = "\n".join(recent) or "_No recent learnings._"
except:
    learnings_section = "_Learnings log unavailable._"

# Confetti Closet
cc_website = "✅" if confetti.get("has_website") else "❌"
cc_intake = "✅" if confetti.get("has_intake_form") else "❌"
cc_skill = "✅" if confetti.get("has_skill") else "❌"
cc_posts = confetti.get("posts_this_week", "?")
confetti_section = f"""- Website: {cc_website}
- Intake form: {cc_intake}
- Skill: {cc_skill}
- Posts this week: {cc_posts}"""

# Tonight's build
if recent_builds:
    b = recent_builds[0]
    build_section = f"**{b.get('date', '?')}**\n{b.get('detail', '')[:300]}"
else:
    build_section = "_No recent builds._"

# Build the markdown
import subprocess
tz_time = subprocess.check_output(
    ["bash", "-c", 'TZ=America/Chicago date +"%I:%M %p"'],
    text=True
).strip()

gen_time = subprocess.check_output(
    ["bash", "-c", 'date +"%A, %B %d @ %I:%M %p %Z"'],
    text=True
).strip()

briefing = f"""# Nightly Briefing — {today}

**Generated:** {gen_time}  
**For:** Master Chris — morning context before the day starts

---

## ⚡ What Changed Today

{changes}

---

## 🔴 Active Crons — Broken / Needs Attention

{cron_section}

---

## 📅 Today's Agenda

{agenda}

---

## 📌 Active Tasks

{active_tasks}

---

## 🧠 Fresh Learnings (last entries)

{learnings_section}

---

## 🏪 Confetti Closet Status

{confetti_section}

---

## 🔨 Tonight's Build

{build_section}

---

## 🔮 Tomorrow

{tomorrow}

---

*Generated by Overnight Builder — {tz_time}*
"""

with open(briefing_file, "w") as f:
    f.write(briefing)

print(f"✅ Briefing written: {briefing_file}")
print(f"   ({len(briefing.splitlines())} lines)")
print()
print("--- PREVIEW ---")
print(briefing[:800])
print("...[truncated]...")
PYEOF
